server:
  port: 18800

spring:
  cloud:
    gateway:
      routes:
        - id: sapphire-auth
          uri: lb://sapphire-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: sapphire-web
          uri: lb://sapphire-web
          predicates:
            - Path=/web/**
          filters:
            - StripPrefix=1
